### ISSUE TITLE
support for sdmmc card?

### ISSUE THREAD

**Issue by zhjygit** [aresta/ESP32_GPS#2]
How can i implant the code to my board,with sdmmc card(not spi SD card).\
Otherwise, my tft display is GT911 touch lcd-4.3, there is no joystick.
In summary, my board is esp32s3-groom-1-N16R8,with sdmmc type tf card,with GT911 4.3 lcd, how can i implant the code?
Waiting for you reply.
Here is my board datasheet:
[Uploading 4.3寸开发板原理图.pdf…]()

**Comment by aresta** [comment]
Hello, 
 for other types of card you need to find and use the libraries to access it and be able to read the files in it, with FS.
The same for your display, you have to use the corresponding driver. Also adapt the code to use the touch screen to move and zoom instead of the joystick.
Take into account that this is a work in progress and for the moment I only have my devices to test. But I will be happy to help you and support to make the code more modular to support other devices.
